
CREATE TABLE ORGANIZATIONS 조직도
(
  UNIQUE_ID        VARCHAR(200) NOT NULL COMMENT '대표값',
  DEPARTMENT       VARCHAR(200) NULL     COMMENT '부서명',
  UNIQUE_ID_PARENT VARCHAR(200) NOT NULL COMMENT '상위대표값',
  PRIMARY KEY (UNIQUE_ID)
);

ALTER TABLE ORGANIZATIONS 조직도
  ADD CONSTRAINT FK_ORGANIZATIONS 조직도_TO_ORGANIZATIONS 조직도
    FOREIGN KEY (UNIQUE_ID_PARENT)
    REFERENCES ORGANIZATIONS 조직도 (UNIQUE_ID);
